//======== (C) Copyright 2002 Charles G. Cleveland All rights reserved. =========
//
// The copyright to the contents herein is the property of Charles G. Cleveland.
// The contents may be used and/or copied only with the written permission of
// Charles G. Cleveland, or in accordance with the terms and conditions stipulated in
// the agreement/contract under which the contents have been supplied.
//
// Purpose: 
//
// $Workfile:  $
// $Date: $
//
//-------------------------------------------------------------------------------
// $Log: $
//===============================================================================
#ifndef AVH_COMMAND_CONSTANTS_H
#define AVH_COMMAND_CONSTANTS_H

// Commands
//#define kcBuyReinforcements			"buyreinforcements"
#define kcReadyRoom					"readyroom"
#define kcMenuReadyRoom					"menureadyroom"
#define kcJoinTeamOne				"jointeamone"
#define kcJoinTeamTwo				"jointeamtwo"
#define kcJoinTeamThree				"jointeamthree"
#define kcJoinTeamFour				"jointeamfour"
#define kcSpectate					"spectate"
#define kcAutoAssign				"autoassign"
#define kcPlayHUDSound				"playhudsound"
#define kcStartGame					"startgame"
#define kcSwitch					"switch"
#define kcSetTeam					"setteam"
#define kcEndGame					"endgame"
#define kcAdjustScore				"adjustscore"
#define kcGivePoints				"givepoints"
#define kcGiveUpgrade				"giveupgrade"
#define kcRemoveUpgrade				"removeupgrade"
#define kcSetRole					"setrole"
#define kcSpawnEnemy				"spawnenemy"
#define kcEquipOne					"equip1"
#define kcEquipTwo					"equip2"
#define kcEquipThree				"equip3"
#define kcKillAlien					"killalien"
#define kcGiveArmor					"givearmor"
#define kcGlobalChat				"messagemode"
#define kcTeamChat					"messagemode2"
#define kcNearbyChat				"messagemode3"
#define kcSetGamma					"setgamma"
#define kcStartCommandMode			"startcommandermode"
#define kcStopCommandMode			"stopcommandermode"
#define kcSetCullDistance			"setculldistance"
#define kcRun						"run"
#define kcClientRun					"clientrun"
#define kcListPS					"listps"
#define kcEditPS					"editps"
#define kcCrash						"crash"
#define kcAssert					"assert"
#define kcBuildMiniMap				"buildminimap"
#define kcNetScreenShot				"netscreenshot"
#define	kcAddCat					"addcat"
#define	kcRemoveCat					"removecat"
#define	kcTestEvent					"testevent"
#define kcRestart					"sv_restart"
#define kcRestartRound				"sv_restartround"
#define kcGetNumPlayers				"getnumplayers"
#define kcKillHive					"killhive"
#define kcKillCS					"killcs"
#define kcAttackCS					"attackcs"
#define kcSpawnHive					"spawnhive"
#define kcAlert						"alert"
#define kcBigDig					"bigdig"
#define kcLowCost					"lowcost"
#define kcHighDamage				"highdamage"
#define kcHighTech					"hightech"
#define kcSlowResearch				"slowresearch"
#define kcDetectAll					"detectall"
#define kcInvul						"invul"
#define kcNumInfos					"numinfos"
#define kcNumSpawns					"numspawns"
#define kcMapUtilNumEnts			"maputil_numents"
#define kcMapUtilEntityInfo			"maputil_entityinfo"
#define kcEntityInfo				"entityinfo"
#define kcOrderSelf					"orderself"
#define	kcParasite					"parasite"
#define kcKillAll					"killall"
#define kcAuth						"auth"
#define kcStun						"stun"
#define kcBoxes						"boxes"
#define kcOverflow					"overflow"
#define kcSendMessage				"sendmessage"
#define kcTooltip					"tt"
#define kcHurt						"hurt"
#define kcWeb						"web"
#define kcEndGame1					"endgame1"
#define kcEndGame2					"endgame2"
#define kcDeathMessage				"deathmessage"
#define kcSetSkin					"setskin"
#define kcSetAuth					"setauth"
#define kcNumEnts					"numents"
#define kcRedeem					"redeem"
#define kcElectric					"electric"
#define kcViewAll					"viewall"
#define kcHighSpeed					"highspeed"
#define kcRoomType					"roomtype"
#define kcDigest					"digest"
#define kcSetBalanceVar				"setbalancevar"
#define kcNSChangeLevel				"nschangelevel"
#define kcTournyMode				"tournymode"
//#define kcSendParticleTemplates		"sendparticletemplates"

#endif