maps/co_niveus.txt
gfx/env/arcnbk.tga
gfx/env/arcndn.tga
gfx/env/arcnft.tga
gfx/env/arcnlf.tga
gfx/env/arcnrt.tga
gfx/env/arcnup.tga
models/co_niveus/helix.mdl
models/co_niveus/plant_pod2.mdl
sound/co_niveus/steamjet1.wav
sound/co_niveus/steamburst1.wav
sound/co_niveus/bastwind2.wav
sound/co_niveus/bg.wav
sound/co_niveus/hum.wav
sprites/co_niveus/hera_fog.spr
sprites/co_niveus/welddrip.spr
sprites/co_niveus/xsmoke1.spr
sprites/co_niveus/raindrop.spr